Update to release 0.1.1-1

diff --git a/odroid-xu-emmc-fuser b/odroid-xu-emmc-fuser
--- a/odroid-xu-emmc-fuser
+++ b/odroid-xu-emmc-fuser
@@ -5,9 +5,21 @@ if [ -z $1 ]; then
   exit 1
 fi
 
+if [[ $EUID -ne 0 ]]; then
+  echo "This script must be run as root"
+  exit 4
+fi
+
 if [ -b $1 ]; then
   if [ -b $1boot0 ]; then
-    echo -n "Fusing boot blob to $1boot0..."
+    devname=`echo $1boot0 | awk -F/ '{ print $NF }'`
+    if [ -f /sys/class/block/$devname/force_ro ] && echo 0 > /sys/class/block/$devname/force_ro; then
+      echo "Successfully enabled write access to $1boot0."
+      do_force_ro=1
+    else
+      echo "WARNING: Failed to enable write access to $1boot0. Proceeding anyway..."
+    fi
+    echo "Fusing boot blob to $1boot0..."
   else
     echo "$1 has no boot partition!"
     exit 3
@@ -17,7 +29,18 @@ else
   exit 2
 fi
 
-dd iflag=dsync oflag=dsync if=@bootblobpath@ of=$1boot0
+RET=0
+dd iflag=dsync oflag=dsync if=@bootblobpath@ of=$1boot0 || RET=$?
 
-echo "Success!"
-exit 0
+if [ "$do_force_ro" == "1" ]; then
+  echo 1 > /sys/class/block/$devname/force_ro
+fi
+
+if [ $RET -ne 0 ]; then
+  echo "Failed!"
+else
+  echo "Success!"
+fi
+
+exit $RET
+
diff --git a/odroid-xu-sd-fuser b/odroid-xu-sd-fuser
--- a/odroid-xu-sd-fuser
+++ b/odroid-xu-sd-fuser
@@ -6,13 +6,19 @@ if [ -z $1 ]; then
 fi
 
 if [ -b $1 ]; then
-  echo -n "Fusing boot blob to $1..."
+  echo "Fusing boot blob to $1..."
 else
   echo "$1 is not a block device!"
   exit 2
 fi
 
-dd iflag=dsync oflag=dsync if=@bootblobpath@ of=$1 seek=1
+RET=0
+dd iflag=dsync oflag=dsync if=@bootblobpath@ of=$1 seek=1 || RET=$?
 
-echo "Success!"
-exit 0
+if [ $RET -ne 0 ]; then
+  echo "Failed!"
+else
+  echo "Success!"
+fi
+
+exit $RET
